//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abouts
    {
        public int Id { get; set; }
        public string Info { get; set; }
        public string Education { get; set; }
        public string Experiences { get; set; }
    }
}
