//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntityEntities : DbContext
    {
        public DbCvEntityEntities()
            : base("name=DbCvEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abilities> Abilities { get; set; }
        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Works> Works { get; set; }
    }
}
